# Tensorflow
Tensor flow is an open-source end-to-end machine learning library for data processing, data modelling and serving models

## Introduction to Tensors

tensor can be looked at as a multi-dimentional numerical represenation of something. Where something can be almost anything. It can be:
 - numbers themselves (using tensors to represent the price of houses).
 - an image (using tensors to represent the pixels of an image).
 - text (using tensors to represent words).
 - some other form of information (or data) you want to represent with numbers.


The main difference between tensors and NumPy arrays (also an n-dimensional array of numbers) is that tensors can be used on GPUs (graphical processing units) and TPUs (tensor processing units).

The benefit of being able to run on GPUs and TPUs is faster computation, this means, if we wanted to find patterns in the numerical representations of our data, we can generally find them faster using GPUs and TPUs.

In [1]:
# import tensorflow library under the common alias tf
import tensorflow as tf
print(tf.__version__) # print the version of tensorflow

2.4.1


## Creating Tensors with tf.constant()
In general, you usually won't create tensors yourself as tensorFlow has modules built-in (such as tf.io and tf.data) which are able to read your data sources and automatically convert them to tensors and then later on, neural network models will process these for us.

To understand tensors,We'll begin by using tf.constant().

In [2]:
# create a scalar (rank 0 tensor)
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>


A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).

*tensors can have an unlimited range of dimensions (the exact amount will depend on what data you're representing).*

In [3]:
# Check the number of dimensions of a tensor
scalar.ndim # ndim stands for number of dimensions

0

In [4]:
# create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
# check number of dimensions of vector
vector.ndim

1

In [11]:
# create a matrix with more than one dimension
matrix = tf.constant([[10,5,3],[12,1,21],[1,2,12]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  5,  3],
       [12,  1, 21],
       [ 1,  2, 12]])>

In [12]:
matrix.ndim

2


By default, TensorFlow creates tensors with either an int32 or float32 datatype.This is known as **32-bit precision** *(the higher the number, the more precise the number, the more space it takes up on your computer).*

In [13]:
#defining datatype in tensor
mat = tf.constant([[10., 8.],[3.1,3.2]],dtype=tf.float16)
mat

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10. ,  8. ],
       [ 3.1,  3.2]], dtype=float16)>

In [14]:
# dimensions remain same as matrix
mat.ndim

2

In [17]:
# creating an tensor with more than 2 dimensions
t = tf.constant([[[1,2],[2,1]],[[3,4],[34,43]],[[45,54],[5,4]]])
t

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 2,  1]],

       [[ 3,  4],
        [34, 43]],

       [[45, 54],
        [ 5,  4]]])>

In [18]:
t.ndim

3


This is known as a rank 3 tensor (3-dimensions), however a tensor can have an arbitrary amount of dimensions.

For example:
 you might turn a series of images into tensors with shape (224, 224, 3, 32), where:
  - 224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
  - 3 is the number of colour channels of the image (red, green blue)
  - 32 is the batch size (the number of images a neural network sees at any one time).


## Creating Tensors with tf.Variable()
You can also create tensors using tf.Variable().The difference between tf.Variable() and tf.constant() is tensors created with tf.constant() are immutable, where as, tensors created with tf.Variable() are mutable.

In [19]:
ct = tf.constant([10,3])
vt = tf.Variable([421,12])
ct,vt

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([421,  12])>)

In [22]:
vt[0] =7
vt

TypeError: 'ResourceVariable' object does not support item assignment

In [25]:
vt[0].assign(12728)
print(vt)
ct[0].assign(121)
ct

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12728,    12])>


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating random tensors
Random tensors are tensors of some abitrary size which contain random numbers.This is what neural networks use to intialize their weights (patterns) that they're trying to learn in the data.

The process of a neural network learning often involves taking a random n-dimensional array of numbers and refining them until they represent some kind of pattern

In [26]:
# create random tensors ; set  the seed to reproduce the same result
rand_1 = tf.random.Generator.from_seed(50)
rand_1= rand_1.normal(shape =(4,2)) #tensor from normal distribution
rand_2 = tf.random.Generator.from_seed(50)
rand_2 = rand_2.normal(shape=(4,2))
rand_1,rand_2

(<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[ 0.45331386,  1.1487608 ],
        [-1.2659091 , -0.47450137],
        [ 2.006022  ,  0.28288034],
        [-0.30288252, -1.443651  ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[ 0.45331386,  1.1487608 ],
        [-1.2659091 , -0.47450137],
        [ 2.006022  ,  0.28288034],
        [-0.30288252, -1.443651  ]], dtype=float32)>)

In [27]:
rand_2 == rand_1

<tf.Tensor: shape=(4, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])>

In [30]:
# shuffle a tensor (Mainly used to shuffle the data)
unshuffled = tf.constant([[12,32],
                          [21,211],
                          [43,12]])
#shuffling gets different results each time
tf.random.shuffle(unshuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 21, 211],
       [ 43,  12],
       [ 12,  32]])>

In [44]:
# shuffle in the same order everytime using seed parameters
tf.random.shuffle(unshuffled,seed =50)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 43,  12],
       [ 12,  32],
       [ 21, 211]])>

As observed the numbers dont come out the same

It's due to rule #4 of the tf.random.set_seed() documentation.

 *"If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."*
 
tf.random.set_seed(50) sets the global seed, and the seed parameter in tf.random.shuffle(seed=50) sets the operation seed.Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."

In [54]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42) # if this line is commented the results will be different

# Set the operation random seed
tf.random.shuffle(unshuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 12,  32],
       [ 21, 211],
       [ 43,  12]])>

In [55]:
# creating tensors of ones and zeros
tf.ones(shape =(3,2,5,2))

<tf.Tensor: shape=(3, 2, 5, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]], dtype=float32)>

In [61]:
tf.zeros(shape = (2,2,2,3))

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [64]:
# convert a numpy to tensor
import numpy as np 
np_a = np.arange(12,54, dtype = np.int32) # create a numpy array between 12 and 54
np_a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53])

In [69]:
A  = tf.constant(np_a,shape=[2,3,7]) # The shape must be equal to the number of elements in the array
A

<tf.Tensor: shape=(2, 3, 7), dtype=int32, numpy=
array([[[12, 13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30, 31, 32]],

       [[33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46],
        [47, 48, 49, 50, 51, 52, 53]]])>

## Getting information from tensors (shape, rank, size)
 - Shape: The length (number of elements) of each of the dimensions of a tensor.
 - Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
 - Axis or Dimension: A particular dimension of a tensor.
 - Size: The total number of items in the tensor.
You'll use these especially when you're trying to line up the shapes of your data to the shapes of your model.


In [70]:
ten = tf.zeros([3,4,1,4])
ten

<tf.Tensor: shape=(3, 4, 1, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]]]], dtype=float32)>

In [71]:
ten.shape,ten.ndim,tf.size(ten)

(TensorShape([3, 4, 1, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=48>)

In [74]:
# getting various attributes of tensor
print("Datatype of every element:",ten.dtype)
print("Number of dimensions(rank):",ten.ndim)
print("shape of a tensor:",ten.shape)
print("Elements along axis 0 of tensor:",ten.shape[0])
print("Elements along last axis of tensor:",ten.shape[-1])
print("Total number of elements (3*4*1*4):",tf.size(ten).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions(rank): 4
shape of a tensor: (3, 4, 1, 4)
Elements along axis 0 of tensor: 3
Elements along last axis of tensor: 4
Total number of elements (3*4*1*4): 48


In [80]:
#get items of each dimensions
ten[:3,:1,:1,:1], ten[:,:2,:1,:]

(<tf.Tensor: shape=(3, 1, 1, 1), dtype=float32, numpy=
 array([[[[0.]]],
 
 
        [[[0.]]],
 
 
        [[[0.]]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 1, 4), dtype=float32, numpy=
 array([[[[0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.]]]], dtype=float32)>)

In [81]:
two = tf.constant([[12,1],[12,3]])
two[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3])>


You can also add dimensions to your tensor whilst keeping the same information present using tf.newaxis.

In [82]:
rank_3 = two[..., tf.newaxis] # in python "..." means " all dimensions prior to"
two,rank_3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[12,  1],
        [12,  3]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[12],
         [ 1]],
 
        [[12],
         [ 3]]])>)

You can achieve the same using tf.expand_dims().

In [83]:
tf.expand_dims(two,axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[12],
        [ 1]],

       [[12],
        [ 3]]])>

## Manipulating tensors (tensor operations)
Finding patterns in tensors requires manipulating them.

### Basic operations
You can perform many of the basic mathematical operations directly on tensors using Pyhton operators such as, +, -, *.

In [86]:
tensor = tf.constant([[1,3],[6,4]])
tensor+10, tensor # Since we used tf.constant(), the original tensor is unchanged (the addition gets done on a copy).

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 13],
        [16, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 3],
        [6, 4]])>)

In [87]:
tensor*10,tensor-10,tensor/10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 30],
        [60, 40]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-9, -7],
        [-4, -6]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[0.1, 0.3],
        [0.6, 0.4]])>)

In [88]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 30],
       [60, 40]])>

## Matrix mutliplication

In [89]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 15],
       [30, 34]])>

In [91]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 15],
       [30, 34]])>

The main two rules for matrix multiplication to remember are:
 - The inner dimensions must match:
    - (3, 5) @ (3, 5) won't work
    - (5, 3) @ (3, 5) will work
    - (3, 5) @ (5, 3) will work
 - The resulting matrix has the shape of the inner dimensions:
    - (5, 3) @ (3, 5) -> (5, 5)
    - (3, 5) @ (5, 3) -> (3, 3)

In [108]:
A = tf.constant([[1,2],[2,3],[3,4]])
B = tf.constant([[1,2,4],[2,3,1]])
C = tf.constant([[1,2,1],[2,3,4],[3,4,6]])
D = tf.constant([[1],[2],[3]])
print(A.shape,B.shape)
print(A@B)
print(A.shape,C.shape)
print(A@C)

(3, 2) (2, 3)
tf.Tensor(
[[ 5  8  6]
 [ 8 13 11]
 [11 18 16]], shape=(3, 3), dtype=int32)
(3, 2) (3, 3)


InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,3] [Op:MatMul]

In [103]:
print(A.shape,D.shape)
A@D

(3, 2) (3, 1)


InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,1] [Op:MatMul]

In [105]:
print(B.shape,C.shape)
B@C

(2, 3) (3, 3)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[17, 24, 33],
       [11, 17, 20]])>

In [106]:
print(B.shape,D.shape)
B@D

(2, 3) (3, 1)


<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[17],
       [11]])>

In [107]:
print(C.shape,D.shape)
C@D

(3, 3) (3, 1)


<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 8],
       [20],
       [29]])>

In [109]:
# reshaping the tensors
# tf.reshape() - allows us to reshape a tensor into a defined shape.
# tf.transpose() - switches the dimensions of a given tensor.
D@tf.reshape(D,(1,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])>

In [110]:
tf.matmul(D,tf.transpose(D))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])>

In [111]:
# You can achieve the same result with parameters
tf.matmul(a=D, b=D, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]])>

## The dot product
Multiplying matrices by eachother is also referred to as the dot product.

You can perform the tf.matmul() operation using tf.tensordot().

In [113]:
# Perform matrix multiplication between D and D (transposed)
tf.matmul(D, tf.transpose(D))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])>

In [114]:
# Perform matrix multiplication between D and D (reshaped)
tf.matmul(D, tf.reshape(D, (1, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])>

In [116]:
# Check shapes of D, reshaped D and tranposed D
D.shape, tf.reshape(D, (1, 3)).shape, tf.transpose(D).shape

(TensorShape([3, 1]), TensorShape([1, 3]), TensorShape([1, 3]))

In [118]:
D = tf.constant([[7,8],[2,1],[42,5]])
# Check values of D, reshape D and tranposed D
print("Normal D:")
print(D, "\n") # "\n" for newline

print("D reshaped to (2, 3):")
print(tf.reshape(D, (2, 3)), "\n")

print("D transposed:")
print(tf.transpose(D))

Normal D:
tf.Tensor(
[[ 7  8]
 [ 2  1]
 [42  5]], shape=(3, 2), dtype=int32) 

D reshaped to (2, 3):
tf.Tensor(
[[ 7  8  2]
 [ 1 42  5]], shape=(2, 3), dtype=int32) 

D transposed:
tf.Tensor(
[[ 7  2 42]
 [ 8  1  5]], shape=(2, 3), dtype=int32)



The outputs of tf.reshape() and tf.transpose() when called on D, even though they have the same shape, are different.

tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear
.
tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.

## Changing the datatype of a tensor
This is common when you want to compute using less precision (e.g. 16-bit floating point numbers vs. 32-bit floating point numbers).
Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).

You can change the datatype of a tensor using tf.cast().

In [119]:
tensor = tf.constant([2,5])
tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

In [121]:
tensor = tf.cast(tensor,dtype = tf.float16)
tensor

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2., 5.], dtype=float16)>

In [122]:
tensor = tf.cast(tensor,dtype = tf.int16)
tensor

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([2, 5], dtype=int16)>

## Getting the absolute value
Sometimes you'll want the absolute values (all values are positive) of elements in your tensors.

To do so, you can use tf.abs().

In [123]:
tf.abs(tensor)

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([2, 5], dtype=int16)>

## Finding the min, max, mean, sum (aggregation)

aggregation methods typically have the syntax reduce()_[action], such as:
 - tf.reduce_min() - find the minimum value in a tensor.
 - tf.reduce_max() - find the maximum value in a tensor.
 - tf.reduce_mean() - find the mean of all elements in a tensor.
 - tf.reduce_sum() - find the sum of all elements in a tensor.

Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

In [131]:
# create a tensor with 50 random values
ten = tf.constant(np.random.randint(low =-500,high=100, size =50))
ten = tf.cast(ten, dtype=tf.float32)

In [132]:
# min max mean and sum
tf.reduce_min(ten),tf.reduce_max(ten),tf.reduce_mean(ten),tf.reduce_sum(ten)

(<tf.Tensor: shape=(), dtype=float32, numpy=-494.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=88.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-230.66>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-11533.0>)

In [133]:
# standard deviation and varaince
tf.math.reduce_std(ten), tf.math.reduce_variance(ten)

(<tf.Tensor: shape=(), dtype=float32, numpy=182.07466>,
 <tf.Tensor: shape=(), dtype=float32, numpy=33151.184>)